from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from .forms import SubmitButtonWidget
from .site_scrape_plp.main_ import run_script
from multiprocessing import Process, Pool
from pathlib import Path
import os.path

from openpyxl import Workbook
from openpyxl.writer.excel import save_virtual_workbook


live = [['https://www.joules.com']]
staging = [['https://uk-staging.prod.joules.joules-prod01.aws.eclipsegroup.co.uk/'], ['https://us-staging.prod.joules.joules-prod01.aws.eclipsegroup.co.uk/'], ['https://de-staging.prod.joules.joules-prod01.aws.eclipsegroup.co.uk/']]
uk, us, de = [], [], []
lst = {}

def main(request):
    if request.method == 'POST':
        if 'live' in request.POST.get('env'):
            # run_environment(live)

            # filename = "my-file.txt"
            # content = 'any string generated by django'
            # response = HttpResponse(content, content_type='text/plain')
            # response['Content-Disposition'] = 'attachment; filename={0}'.format(filename)
            # return response

            # file = Path(os.path.abspath(os.path.dirname(__file__))).joinpath('test.xlsx')
            # response = HttpResponse(file, content_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
            # response['Content-Disposition'] = 'attachment; filename=test.xlsx'
            # return response

            workbook = Workbook()
            worksheet = workbook.active

            filename = "myexport.csv"
            response = HttpResponse(content=save_virtual_workbook(workbook), content_type='text/csv')
            response['Content-Disposition'] = 'attachment; filename={0}'.format(filename)

            return response

    else:
        form = SubmitButtonWidget()

    return render(request, 'badges/content.html', {'form': form})

def run_environment(env):
    with Pool(processes=1) as pool:
        p1 = pool.apply_async(run_script, (env[0], ))


